name: Run on push to main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (если нужно)
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm ci

      - name: Set up Chrome
        uses: googlechrome/setup-chrome@v2
        with:
          chrome-version: 'stable'

      - name: Run and build site
        run: |
          npm run start:ui5 &

      - name: Run tests (если нужно)
        run: |
          npm run wdi5
